### ISSUE TITLE
Error with npm test

### ISSUE THREAD

**Issue by MarieTiss** [romi/3d-plantviewer#143]
Command "npm test" is not working. 

Error message : 
Error: Cannot find module './lib/source-map-generator'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/remisans/romi_db/reconstructions/plant-3d-explorer/node_modules/source-map/source-map.js:6:30)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)

Versions used : 
- node v10.0.0
- npm v7.24.2

**Comment by fabfabBesnard** [comment]
also, `npm start` is not working...
so the web client cannot be started !
